# Generated by Django 6.0.1 on 2026-01-20 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails')),
            ],
        ),
    ]
