# Generated by Django 6.0.1 on 2026-02-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('drama', 'Drama'), ('documentary', 'Documentary'), ('romance', 'Romance'), ('comedy', 'Comedy')], default='drama', max_length=50),
        ),
    ]
